### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by will-ca** [ravignir/5Hex-Tileset#5]
Not sure what the current legal status is for inclusion in Unciv and such:

> Regarding the 5Hex assets, I mean that unless Ravignir explicitly gave permission (such as by releasing under CC), then we're technically/legally still not able to use or relicense his art. Not a problem, but more like covering all bases.

https://github.com/yairm210/Unciv/issues/5770

Specifying a license by name in the README ought to change that, if you would like to:

https://creativecommons.org/about/cclicenses/

**Comment by throwaway1037** [comment]
Please may you release under a [libre](https://freedomdefined.org) license, so that the tiles can he used in 100% libre operating system distributions like [Parabola](https://parabola.nu)?

I'd recommend CC-BY-SA-4.0-Int-or-later.

**Comment by ravignir** [comment]
I don't know the legal status either but since the entire repository is only my work, who would sue you if i am not going to?

**Comment by throwaway1037** [comment]
@ravignir if you don't release under a libre license then what Unciv is doing is illegal.

**Comment by throwaway1037** [comment]
More generally, if you don't release under a libre license, then anybody who copies the repo is breakin the law.

**Comment by yairm210** [comment]
> @ravignir if you don't release under a libre license then what Unciv is doing is illegal.

This is untrue, since we have *direct* owner agreement



> More generally, if you don't release under a libre license, then anybody who copies the repo is breaking the law.

This however is correct. If someone wants to use your images, they'll need explicit permission from you.

**Comment by throwaway1037** [comment]
@yairm210 my mistake, I apologise. I was not aware of such an agreement.

However, the request still stands: please may you release under a libre license so that libre distros like Parabola can package the tileset and as a result make software which uses it such as Unciv playable?

**Comment by throwaway1037** [comment]
:(

To elaborate, if I may: the issue is that distributions which cannot package proprietary files will be excluded entirely from packaging this tileset, and as a result, any dependencies such as Unciv will be entirely excluded from official repositories for those systems.
This unnecessarily excludes lots of people from ever playing Unciv in the first place, and removes the potential for people for people who would otherwise have been able to play Unciv and see the tileset from contributing back to either project, which would be a tremendous shame.

The issue is not that the authors would sue Unciv; as I said, I apologise for making that mistake.
However, anybody else who would want to use the tileset would be liable to be sued, which is not ideal.

Please may we discuss this issue further, if that's okay?

**Comment by ravignir** [comment]
`This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.`

I've added this to readme. Anything else i need to do? :"D

**Comment by throwaway1037** [comment]
Thank you, that's legalised several uses for the tileset!
However, it's not a libre license; unfortunately, the non-commercial restriction would prevent it from being included in libre repos.
Eg. If I put Unciv and the tileset on a USB stick and then sold the USB stick to a friend, I might still be liable to be sued because it could be regarded as selling the tileset (obligatory I am not a lawyer).

https://freedomdefined.org has the definition of libre works, a list of free licenses, and an essay about the NC restriction.

A libre license would be CC-BY-SA-4.0-Int-or-later (not specifying "only" or "or-later" leaves ambiguity in the licensing), and a copy of the license would preferably need to be put in the repo.

Again, thank you :)
